<a href="https://colab.research.google.com/github/charvimaini7/Sk-learn-Practice/blob/main/MLP_Mock.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import FunctionTransformer
from sklearn.datasets import load_iris
from sklearn.preprocessing import PolynomialFeatures
from sklearn.datasets import fetch_california_housing
from sklearn.feature_selection import SelectPercentile, mutual_info_regression
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyRegressor
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_diabetes
from sklearn.linear_model import RidgeCV

In [ ]:
X,y = load_breast_cancer(return_X_y= True, as_frame = True)

In [ ]:
X.shape

(569, 30)

In [ ]:
y.unique()

array([0, 1])

In [ ]:
y.value_counts()

1    357
0    212
Name: target, dtype: int64

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [ ]:
# X['mean perimeter'].corr(['mean radius'])
X.corr()

mean radius  mean texture  mean perimeter  mean area  \
mean radius                 1.000000      0.323782        0.997855   0.987357   
mean texture                0.323782      1.000000        0.329533   0.321086   
mean perimeter              0.997855      0.329533        1.000000   0.986507   
mean area                   0.987357      0.321086        0.986507   1.000000   
mean smoothness             0.170581     -0.023389        0.207278   0.177028   
mean compactness            0.506124      0.236702        0.556936   0.498502   
mean concavity              0.676764      0.302418        0.716136   0.685983   
mean concave points         0.822529      0.293464        0.850977   0.823269   
mean symmetry               0.147741      0.071401        0.183027   0.151293   
mean fractal dimension     -0.311631     -0.076437       -0.261477  -0.283110   
radius error                0.679090      0.275869        0.691765   0.732562   
texture error              -0.097317      0.386358       -0.086761  -0.066280   
perimeter error             0.674172      0.281673        0.693135   0.726628   
area error                  0.735864      0.259845        0.744983   0.800086   
smoothness error           -0.222600      0.006614       -0.202694  -0.166777   
compactness error           0.206000      0.191975        0.250744   0.212583   
concavity error             0.194204      0.143293        0.228082   0.207660   
concave points error        0.376169      0.163851        0.407217   0.372320   
symmetry error             -0.104321      0.009127       -0.081629  -0.072497   
fractal dimension error    -0.042641      0.054458       -0.005523  -0.019887   
worst radius                0.969539      0.352573        0.969476   0.962746   
worst texture               0.297008      0.912045        0.303038   0.287489   
worst perimeter             0.965137      0.358040        0.970387   0.959120   
worst area                  0.941082      0.343546        0.941550   0.959213   
worst smoothness            0.119616      0.077503        0.150549   0.123523   
worst compactness           0.413463      0.277830        0.455774   0.390410   
worst concavity             0.526911      0.301025        0.563879   0.512606   
worst concave points        0.744214      0.295316        0.771241   0.722017   
worst symmetry              0.163953      0.105008        0.189115   0.143570   
worst fractal dimension     0.007066      0.119205        0.051019   0.003738   

                         mean smoothness  mean compactness  mean concavity  \
mean radius                     0.170581          0.506124        0.676764   
mean texture                   -0.023389          0.236702        0.302418   
mean perimeter                  0.207278          0.556936        0.716136   
mean area                       0.177028          0.498502        0.685983   
mean smoothness                 1.000000          0.659123        0.521984   
mean compactness                0.659123          1.000000        0.883121   
mean concavity                  0.521984          0.883121        1.000000   
mean concave points             0.553695          0.831135        0.921391   
mean symmetry                   0.557775          0.602641        0.500667   
mean fractal dimension          0.584792          0.565369        0.336783   
radius error                    0.301467          0.497473        0.631925   
texture error                   0.068406          0.046205        0.076218   
perimeter error                 0.296092          0.548905        0.660391   
area error                      0.246552          0.455653        0.617427   
smoothness error                0.332375          0.135299        0.098564   
compactness error               0.318943          0.738722        0.670279   
concavity error                 0.248396          0.570517        0.691270   
concave points error            0.380676          0.642262        0.683260   
symmetry error                 

In [ ]:
si = SimpleImputer()

In [ ]:
X = np.array([[7, 16, 31], [np.nan, np.nan, 66], [12, 5, np.nan],[98, np.nan, 92]])
X_new = si.fit_transform(X)
X_new

array([[ 7. , 16. , 31. ],
       [39. , 10.5, 66. ],
       [12. ,  5. , 63. ],
       [98. , 10.5, 92. ]])

In [ ]:
ft = FunctionTransformer(np.log10)


In [ ]:
X1 = np.array([[1, 1], [2, 3],[10,100]])
X_new1 = ft.fit_transform(X1)
X_new1

array([[0.        , 0.        ],
       [0.30103   , 0.47712125],
       [1.        , 2.        ]])

In [ ]:
X_i,y_i = load_iris(return_X_y = True, as_frame = True)

In [ ]:
X_i.shape

(150, 4)

In [ ]:
po = PolynomialFeatures()

In [ ]:
X_ii = po.fit_transform(X_i)
X_ii.shape

(150, 15)

In [ ]:
X_c,y_c = fetch_california_housing(return_X_y = True, as_frame = True)
X_c.shape

(20640, 8)

In [ ]:
X_c_new = SelectPercentile(mutual_info_regression, percentile=10).fit_transform(X_c, y_c)
X_c_new.shape

(20640, 1)

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X_c,y_c,test_size = 0.2,random_state =1)

In [ ]:
X_train.shape

(16512, 8)

In [ ]:
dummy_regr = DummyRegressor(strategy="mean")

In [ ]:
dummy_regr.fit(X_train,y_train)

DummyRegressor()

In [ ]:
dummy_regr.score(X_test.to_numpy(),y_test.to_numpy())

-0.0014734336890012134

In [ ]:
sgd = SGDRegressor()
pipe = make_pipeline(MinMaxScaler(),sgd)

In [ ]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('minmaxscaler', MinMaxScaler()),
                ('sgdregressor', SGDRegressor())])

In [ ]:
y_predict_train = pipe.predict(X_train)

In [ ]:
y_predict_test = pipe.predict(X_test)

In [ ]:
mean_absolute_error(y_train,y_predict_train)

0.5645728199979614

In [ ]:
mean_absolute_error(y_test,y_predict_test)

0.5629197702363613

In [ ]:
lr = LinearRegression()

In [ ]:
MS = MinMaxScaler()
# X1 = MS.fit_transform(X_train)
# y1 = MS.fit_transform(y_train.to_numpy().reshape(-1,1))
score = cross_val_score(lr,X_c,y_c, cv=5)
score


array([0.54866323, 0.46820691, 0.55078434, 0.53698703, 0.66051406])

In [ ]:
X_d,y_d = load_diabetes(return_X_y= True, as_frame = True)

In [ ]:
X_d

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [ ]:
X_train_d,X_test_d,y_train_d,y_test_d = train_test_split(X_d,y_d,test_size = 0.2,random_state =10)

In [ ]:
pipe1 = make_pipeline(StandardScaler(),lr)

In [ ]:
pipe1.fit(X_train_d,y_train_d)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [ ]:
pipe1.score(X_test_d,y_test_d)

0.5341988244945843

In [ ]:
pipe1[1].coef_

array([ -0.1850394 , -10.74378586,  23.97110665,  15.4460079 ,
       -33.6348803 ,  19.07653925,   3.87696491,  10.51802947,
        34.1537076 ,   1.91366485])

In [ ]:
rc = RidgeCV(alphas=np.logspace(-4,0,num=20),  fit_intercept=True, scoring="neg_mean_absolute_error", cv=5, gcv_mode=None, store_cv_values=False, alpha_per_target=False)

In [ ]:
rc.fit(X_train_d,y_train_d)

RidgeCV(alphas=array([1.00000000e-04, 1.62377674e-04, 2.63665090e-04, 4.28133240e-04,
       6.95192796e-04, 1.12883789e-03, 1.83298071e-03, 2.97635144e-03,
       4.83293024e-03, 7.84759970e-03, 1.27427499e-02, 2.06913808e-02,
       3.35981829e-02, 5.45559478e-02, 8.85866790e-02, 1.43844989e-01,
       2.33572147e-01, 3.79269019e-01, 6.15848211e-01, 1.00000000e+00]),
        cv=5, scoring='neg_mean_absolute_error')

In [ ]:
p1 = rc.predict(X_train_d)

In [ ]:
mean_absolute_error(y_train_d,p1)

43.47269677372164